#define SHOWOFFLINETEXTCOLOR       LIGHTGREY
#define SHOWOFFLINEBACKCOLOR       DARKGREY
#define SHOWDISCONNECTEDTEXTCOLOR  WHITE
#define SHOWDISCONNECTEDBACKCOLOR  BLUE
#define SHOWUNKNOWNTEXTCOLOR       MAROON
#define SHOWUNKNOWNBACKCOLOR       ORANGE
